spring.application.name=transcricao

spring.datasource.url=jdbc:postgresql://localhost:5432/transcricao
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=300MB
spring.servlet.multipart.max-request-size=300MB

app.armazenamento.diretorio=./uploads

app.ffmpeg.caminho=ffmpeg
app.ffmpeg.duracao-parte-segundos=1500
app.ffmpeg.timeout-minutos=30