ALTER TABLE transcricao ADD COLUMN total_partes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE transcricao ADD COLUMN partes_concluidas INTEGER NOT NULL DEFAULT 0;
ALTER TABLE transcricao ADD COLUMN duracao_parte_segundos INTEGER;

CREATE TABLE transcricao_parte (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transcricao_id UUID NOT NULL REFERENCES transcricao(id) ON DELETE CASCADE,
    numero INTEGER NOT NULL CHECK (numero >= 0),
    texto TEXT NOT NULL,
    CONSTRAINT uk_transcricao_parte UNIQUE (transcricao_id, numero)
);
